[book]
authors = ["Triton Software AG"]
language = "en"
multilingual = false
src = "src"
title = "Triton VM"

[preprocessor.katex]

[output.linkcheck]
warning-policy = "ignore" # most latex will generate a warning
